// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VassaSpraket_TW.Data;

#nullable disable

namespace VassaSpraket_TW.Data.Migrations
{
    [DbContext(typeof(VassaSpraket_TWDbContext))]
    [Migration("20230920064451_create_table_insertdata")]
    partial class create_table_insertdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VassaSpraket_TW.Data.Models.Chapters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("VassaSpraket_TW.Data.Models.LabelCanvasPos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Canvas_Height")
                        .HasColumnType("int");

                    b.Property<int>("Canvas_StartX")
                        .HasColumnType("int");

                    b.Property<int>("Canvas_StartY")
                        .HasColumnType("int");

                    b.Property<int>("Canvas_Width")
                        .HasColumnType("int");                  

                    b.Property<string>("LabelCanvas_Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelCanvas_Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelCanvas_Top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelCanvas_Width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("PageTemplateId")
                        .HasColumnType("int");

                    b.Property<float>("Scale")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PageTemplateId");

                    b.ToTable("LabelCanvasPos", (string)null);
                });

            modelBuilder.Entity("VassaSpraket_TW.Data.Models.PageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("PdfSrc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PageTemplate", (string)null);
                });

            modelBuilder.Entity("VassaSpraket_TW.Data.Models.LabelCanvasPos", b =>
                {
                    b.HasOne("VassaSpraket_TW.Data.Models.PageTemplate", null)
                        .WithMany("Rows")
                        .HasForeignKey("PageTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VassaSpraket_TW.Data.Models.PageTemplate", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
